"""Shared PDF rendering — branded HTML → PDF via xhtml2pdf (pisa).

Both the plan export (``routes/plan.py``) and the assessment export
(``routes/assess.py``) render a branded, executive-ready document with the same
Databricks styling, page-number footer, and — critically — the same
external-resource backstop. Keeping the CSS, the ``link_callback`` refusal, and
the render/Response mapping in one place means the security hardening (CWE-79 /
CWE-22 / CWE-918) can't drift between the two export paths.

The bodies these functions render are ALWAYS pre-sanitized by the caller with
``markdown_to_safe_html`` (an inert allowlist) before they reach the PDF engine;
``block_external_resources`` is the belt-and-suspenders backstop that refuses any
``src``/``href`` the sanitizer might have missed.
"""

import html as _html
import io
import logging
from datetime import datetime, timezone
from typing import Optional

from fastapi.responses import JSONResponse, Response

from server.security import sanitize_html_fragment

logger = logging.getLogger(__name__)


# Databricks-branded print CSS, shared by every export. A4, an orange rule under
# the title, and a page-number footer frame. xhtml2pdf-specific properties
# (``-pdf-*``, ``<pdf:pagenumber>``) are load-bearing — pisa reads them.
PDF_CSS = """
@page {
  size: A4; margin: 2.2cm 2cm;
  @frame footer { -pdf-frame-content: footerContent; left: 2cm; width: 17cm; bottom: 1.2cm; height: 1cm; }
}
body { font-family: Helvetica, Arial, sans-serif; font-size: 10.5pt; color: #1B3139; line-height: 1.5; }
h1 { color: #1B3139; font-size: 19pt; border-bottom: 3px solid #FF3621; padding-bottom: 6px; margin: 0 0 4px 0; }
.subtitle { color: #5B6B70; font-size: 9pt; margin-bottom: 16px; }
h2 { color: #1B3139; font-size: 13pt; margin-top: 18px; border-bottom: 1px solid #E3E8E9; padding-bottom: 3px; -pdf-keep-with-next: true; page-break-after: avoid; }
h3 { color: #1B3139; font-size: 11pt; margin-top: 12px; -pdf-keep-with-next: true; page-break-after: avoid; }
ul, ol { margin: 6px 0 6px 0; padding-left: 18px; }
li { margin-bottom: 4px; }
strong { color: #1B3139; }
code { font-family: Courier, monospace; background: #F4F6F6; padding: 1px 3px; }
table { border-collapse: collapse; width: 100%; margin: 8px 0; -pdf-keep-in-frame-mode: shrink; }
th, td { border: 1px solid #D5DCDD; padding: 5px 7px; text-align: left; font-size: 9.5pt; }
th { background: #1B3139; color: #fff; }
.footer { color: #8A9499; font-size: 8pt; text-align: center; }
"""


_DEFAULT_SUBTITLE = "Generated by the Genie Ontology Readiness app · Databricks"


class ExternalResourceBlocked(Exception):
    """Raised when a document references a resource the renderer may not fetch."""


class PdfUnavailableError(RuntimeError):
    """Raised when the report dependencies cannot be imported."""


class PdfRenderError(RuntimeError):
    """Raised when the PDF engine cannot render the document."""


def block_external_resources(uri: str, rel: str) -> str:
    """xhtml2pdf resource resolver that refuses every external reference.

    xhtml2pdf resolves ``src``/``href`` on the document it renders, and will
    happily open a ``file://``, absolute-path, or ``http(s)://`` target. Export
    bodies are model-generated and/or round-trip through the client, so without
    this the endpoints are a server-side file read and request forge in one
    (CWE-918, CWE-22): posting ``<img src="file:///…">`` would embed host file
    content into the returned PDF.

    The branded template references no external resource and the body is
    sanitized before it gets here, so this is the backstop: refuse outright
    rather than maintain an allowlist. Raising aborts the render, which is the
    point — a partially-rendered PDF is better than one leaking host files.
    """
    raise ExternalResourceBlocked(uri)


def ensure_pdf_dependencies() -> None:
    """Check the report stack before an assessment or HTTP export starts."""
    try:
        import markdown  # noqa: F401 - availability probe
        from xhtml2pdf import pisa  # noqa: F401 - availability probe
    except Exception as e:
        raise PdfUnavailableError("Install the markdown and xhtml2pdf report dependencies.") from e


def pdf_export_unavailable_response() -> Optional[Response]:
    """A 503 ``Response`` if the optional PDF stack can't be imported, else ``None``.

    Both ``markdown`` and ``xhtml2pdf`` are optional runtime deps. ``markdown`` is
    imported by ``markdown_to_safe_html`` while the document body is BUILT, and
    ``xhtml2pdf`` during render — so gating them together here, before any build,
    keeps the graceful 503 degradation whole. Callers return this at the top of an
    export route so a runtime missing either package degrades that one endpoint
    (503) instead of raising an uncaught 500 mid-build.
    """
    try:
        ensure_pdf_dependencies()
    except Exception as e:  # pragma: no cover - depends on runtime deps
        logger.error(f"PDF engine unavailable: {e}")
        return Response(content="PDF export is unavailable on this deployment.", status_code=503)
    return None


def markdown_to_safe_html(markdown_text: str) -> str:
    """Render Markdown to an inert, allowlisted HTML fragment fit for the PDF engine.

    python-markdown emits raw HTML in the source verbatim, and export bodies are
    model-generated / client-supplied, so the output is sanitized to strip
    resource-loading tags (img/iframe/etc.) that xhtml2pdf would otherwise
    resolve into a local-file read.
    """
    import markdown as md

    return sanitize_html_fragment(
        md.markdown(markdown_text or "", extensions=["tables", "fenced_code", "toc", "sane_lists"])
    )


def build_pdf_document(title: str, body_html: str, *, subtitle: str | None = None) -> str:
    """Assemble the full branded HTML document: title H1, dated subtitle, footer, body.

    ``title`` and ``subtitle`` are HTML-escaped so values containing ``&``/``<``/
    ``>`` can't emit stray tags that break xhtml2pdf. ``body_html`` must already be
    sanitized (see ``markdown_to_safe_html``). Pure/deterministic so it can be
    unit-tested against the real CSS + footer syntax without hitting the network.
    """
    d = datetime.now(timezone.utc)
    generated_on = f"{d:%B} {d.day}, {d.year}"  # portable — avoids the glibc-only %-d
    esc_title = _html.escape(title or "Document")
    esc_subtitle = _html.escape(subtitle or _DEFAULT_SUBTITLE)
    return (
        f"<!DOCTYPE html><html><head><meta charset='utf-8'><style>{PDF_CSS}</style></head>"
        f"<body>"
        f"<div id='footerContent' class='footer'>Genie Ontology Readiness · Databricks · "
        f"page <pdf:pagenumber> of <pdf:pagecount></div>"
        f"<h1>{esc_title}</h1>"
        f"<div class='subtitle'>{esc_subtitle} · {generated_on}</div>"
        f"{body_html}</body></html>"
    )


def render_pdf_bytes(html_doc: str) -> bytes:
    """Render a sanitized document without requiring an HTTP response."""
    try:
        from xhtml2pdf import pisa
    except Exception as e:
        raise PdfUnavailableError("Install xhtml2pdf to render PDF reports.") from e

    buf = io.BytesIO()
    try:
        result = pisa.CreatePDF(
            src=html_doc, dest=buf, encoding="utf-8", link_callback=block_external_resources
        )
    except ExternalResourceBlocked:
        raise
    except Exception as e:
        raise PdfRenderError("PDF generation failed.") from e
    if result.err:
        raise PdfRenderError("PDF generation failed.")
    return buf.getvalue()


def render_pdf_response(html_doc: str, filename_base: str) -> Response:
    """Render a branded HTML document to a PDF ``Response`` (inline for a new-tab viewer).

    The PDF engine is imported lazily so that, if the optional deps fail to load
    in the runtime, only the export endpoints degrade (503) — the rest of the app
    keeps working. Every external/file reference is refused via
    ``block_external_resources`` (400), and a genuine render failure is a 500.
    """
    try:
        content = render_pdf_bytes(html_doc)
    except PdfUnavailableError as e:  # pragma: no cover - depends on runtime deps
        logger.error(f"PDF engine unavailable: {e}")
        return Response(content="PDF export is unavailable on this deployment.", status_code=503)
    except ExternalResourceBlocked as e:
        # Unreachable for a sanitized body; if it does fire, the document asked for
        # something it may not have, which is the caller's problem, not a server fault.
        logger.warning("PDF export refused an external resource reference: %.120s", str(e))
        return JSONResponse(
            status_code=400,
            content={"error": "The document references an external resource and cannot be exported."},
        )
    except PdfRenderError:
        logger.exception("PDF generation failed")
        return Response(content="PDF generation failed", status_code=500)
    safe = "".join(c if c.isalnum() or c in "-_ " else "_" for c in filename_base).strip() or "document"
    return Response(
        content=content,
        media_type="application/pdf",
        headers={"Content-Disposition": f'inline; filename="{safe}.pdf"'},
    )
